'use client';

import { useCallback, useEffect, useState } from 'react';
import { useParams, useSearchParams, useRouter } from 'next/navigation';
import { jsPDF } from 'jspdf';
import { useAuth } from '@/lib/auth-context';
import { ApiException } from '@/lib/api';
import { formatPrice } from '@/lib/types';
import { IconArrowLeft, IconDownload } from '@/components/icons';

interface InvoiceData {
  invoice: {
    id: string;
    number: string;
    kind: string;
    description: string;
    interval: string;
    amountCents: number;
    currency: string;
    status: string;
    periodStart: string | null;
    periodEnd: string | null;
    paidAt: string;
  };
  billTo: { name: string; email: string; address: string };
  seller: { name: string; detail: string; email: string };
}

function fmtDate(iso?: string | null) {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
}

const INK = '#1a1c3a';
const GRAY = '#6b7280';
const FAINT = '#9ca3af';
const LINE = '#e5e7eb';
const GREEN = '#15803d';

/** Build a clean, vector PDF from the invoice data and save it directly. */
function downloadInvoicePdf(d: InvoiceData) {
  const { invoice: inv, billTo, seller } = d;
  const money = (c: number) => formatPrice(c, inv.currency).replace(/ /g, ' ');
  const period = inv.periodStart && inv.periodEnd ? `${fmtDate(inv.periodStart)} - ${fmtDate(inv.periodEnd)}` : '';

  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const W = 612;
  const M = 48;
  const right = W - M;
  let y = 64;

  // Header
  doc.setTextColor(INK).setFont('helvetica', 'bold').setFontSize(18).text(seller.name, M, y);
  doc.setFontSize(22).text('INVOICE', right, y, { align: 'right' });
  y += 18;
  doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(GRAY).text(seller.detail, M, y);
  doc.text(inv.number, right, y, { align: 'right' });
  y += 13;
  if (seller.email) doc.text(seller.email, M, y);
  doc.setTextColor(inv.status === 'paid' ? GREEN : '#b45309').setFont('helvetica', 'bold').text(inv.status.toUpperCase(), right, y, { align: 'right' });
  y += 20;
  doc.setDrawColor(LINE).line(M, y, right, y);
  y += 26;

  // Parties + dates
  doc.setFont('helvetica', 'bold').setFontSize(8).setTextColor(FAINT);
  doc.text('BILLED TO', M, y);
  doc.text('INVOICE DATE', right, y, { align: 'right' });
  y += 15;
  doc.setFont('helvetica', 'bold').setFontSize(11).setTextColor(INK).text(billTo.name, M, y);
  doc.setFont('helvetica', 'normal').setFontSize(10).text(fmtDate(inv.paidAt), right, y, { align: 'right' });
  let leftY = y;
  doc.setFontSize(10).setTextColor(GRAY);
  if (billTo.email) { leftY += 14; doc.text(billTo.email, M, leftY); }
  if (billTo.address) for (const ln of billTo.address.split('\n')) { leftY += 13; doc.text(ln, M, leftY); }
  if (period) {
    doc.setFont('helvetica', 'bold').setFontSize(8).setTextColor(FAINT).text('BILLING PERIOD', right, y + 16, { align: 'right' });
    doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(INK).text(period, right, y + 30, { align: 'right' });
  }
  y = Math.max(leftY, y + 30) + 26;

  // Line items
  doc.setDrawColor(LINE).line(M, y, right, y);
  y += 16;
  doc.setFont('helvetica', 'bold').setFontSize(8).setTextColor(FAINT);
  doc.text('DESCRIPTION', M, y);
  doc.text('AMOUNT', right, y, { align: 'right' });
  y += 10;
  doc.line(M, y, right, y);
  y += 22;
  doc.setFont('helvetica', 'bold').setFontSize(11).setTextColor(INK).text(inv.description, M, y);
  doc.text(money(inv.amountCents), right, y, { align: 'right' });
  if (period) { y += 13; doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(FAINT).text(period, M, y); }
  y += 22;
  doc.setDrawColor(LINE).line(M, y, right, y);
  y += 24;

  // Totals
  const labelX = right - 170;
  const totalRow = (label: string, val: string, bold = false, color = GRAY) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal').setFontSize(bold ? 12 : 10).setTextColor(color);
    doc.text(label, labelX, y);
    doc.text(val, right, y, { align: 'right' });
    y += 19;
  };
  totalRow('Subtotal', money(inv.amountCents));
  totalRow('Tax', money(0));
  doc.setDrawColor(LINE).line(labelX, y - 9, right, y - 9);
  totalRow('Total', money(inv.amountCents), true, INK);
  if (inv.status === 'paid') totalRow('Amount paid', money(inv.amountCents), false, GREEN);

  // Footer
  y += 16;
  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(FAINT);
  doc.text(`Thank you for your business. Generated by ${seller.name}.`, W / 2, y, { align: 'center' });

  doc.save(`Invoice-${inv.number}.pdf`);
}

export default function InvoicePage() {
  const params = useParams<{ id: string }>();
  const search = useSearchParams();
  const router = useRouter();
  const { authedRequest } = useAuth();
  const id = typeof params.id === 'string' ? params.id : '';
  const [data, setData] = useState<InvoiceData | null>(null);
  const [error, setError] = useState('');

  const load = useCallback(async () => {
    try {
      setData(await authedRequest<InvoiceData>(`/api/subscription/invoices/${id}`));
    } catch (e) {
      setError(e instanceof ApiException ? e.message : 'Could not load this invoice.');
    }
  }, [authedRequest, id]);

  useEffect(() => { void load(); }, [load]);

  // ?download=1 (or legacy ?print=1) → auto-download the PDF once loaded.
  const [autoDone, setAutoDone] = useState(false);
  useEffect(() => {
    if (data && !autoDone && (search.get('download') === '1' || search.get('print') === '1')) {
      setAutoDone(true);
      const t = setTimeout(() => downloadInvoicePdf(data), 300);
      return () => clearTimeout(t);
    }
  }, [data, search, autoDone]);

  if (error) {
    return (
      <div className="grid min-h-screen place-items-center bg-surface-subtle px-5 text-sm text-neutral-500">{error}</div>
    );
  }
  if (!data) {
    return (
      <div className="grid min-h-screen place-items-center bg-surface-subtle">
        <span className="h-8 w-8 animate-spin rounded-full border-2 border-neutral-200 border-t-brand-600" />
      </div>
    );
  }

  const { invoice: inv, billTo, seller } = data;
  const periodLabel = inv.periodStart && inv.periodEnd ? `${fmtDate(inv.periodStart)} – ${fmtDate(inv.periodEnd)}` : '';

  return (
    <div className="min-h-screen bg-surface-subtle py-10 print:bg-white print:py-0">
      {/* Toolbar (hidden when printing) */}
      <div className="mx-auto mb-5 flex max-w-2xl items-center justify-between px-6 print:hidden">
        <button onClick={() => router.back()} className="inline-flex items-center gap-1.5 text-sm font-semibold text-neutral-500 hover:text-ink">
          <IconArrowLeft size={16} /> Back
        </button>
        <button
          onClick={() => downloadInvoicePdf(data)}
          className="inline-flex items-center gap-2 rounded-full bg-brand-600 px-5 py-2.5 text-sm font-bold text-white shadow-soft transition hover:bg-brand-700"
        >
          <IconDownload size={16} /> Download PDF
        </button>
      </div>

      {/* Invoice sheet */}
      <div className="mx-auto max-w-2xl bg-white p-10 shadow-[0_1px_3px_rgba(15,15,25,0.06)] print:max-w-none print:p-0 print:shadow-none sm:rounded-3xl">
        <div className="flex flex-wrap items-start justify-between gap-4 border-b border-line pb-6">
          <div>
            <div className="text-xl font-extrabold tracking-tight text-[#1a1c3a]">{seller.name}</div>
            <div className="mt-1 text-sm text-neutral-500">{seller.detail}</div>
            {seller.email && <div className="text-sm text-neutral-500">{seller.email}</div>}
          </div>
          <div className="text-right">
            <div className="text-2xl font-extrabold uppercase tracking-tight text-[#1a1c3a]">Invoice</div>
            <div className="mt-1 text-sm font-semibold text-neutral-600">{inv.number}</div>
            <span className={`mt-2 inline-flex rounded-md px-2.5 py-0.5 text-xs font-bold capitalize ${inv.status === 'paid' ? 'bg-success-50 text-success-700' : 'bg-amber-50 text-amber-700'}`}>
              {inv.status}
            </span>
          </div>
        </div>

        {/* Parties + dates */}
        <div className="mt-6 grid gap-6 sm:grid-cols-2">
          <div>
            <div className="text-xs font-semibold uppercase tracking-wide text-neutral-400">Billed to</div>
            <div className="mt-1 font-semibold text-[#1a1c3a]">{billTo.name}</div>
            {billTo.email && <div className="text-sm text-neutral-500">{billTo.email}</div>}
            {billTo.address && <div className="mt-1 whitespace-pre-line text-sm text-neutral-500">{billTo.address}</div>}
          </div>
          <div className="sm:text-right">
            <div className="text-xs font-semibold uppercase tracking-wide text-neutral-400">Invoice date</div>
            <div className="mt-1 text-sm font-medium text-[#1a1c3a]">{fmtDate(inv.paidAt)}</div>
            {periodLabel && (
              <>
                <div className="mt-3 text-xs font-semibold uppercase tracking-wide text-neutral-400">Billing period</div>
                <div className="mt-1 text-sm font-medium text-[#1a1c3a]">{periodLabel}</div>
              </>
            )}
          </div>
        </div>

        {/* Line items */}
        <table className="mt-8 w-full text-sm">
          <thead>
            <tr className="border-b border-line text-left text-xs font-semibold uppercase tracking-wide text-neutral-400">
              <th className="pb-2">Description</th>
              <th className="pb-2 text-right">Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-line/70">
              <td className="py-4">
                <div className="font-semibold text-[#1a1c3a]">{inv.description}</div>
                {periodLabel && <div className="text-xs text-neutral-400">{periodLabel}</div>}
              </td>
              <td className="py-4 text-right font-semibold text-[#1a1c3a]">{formatPrice(inv.amountCents, inv.currency)}</td>
            </tr>
          </tbody>
        </table>

        {/* Totals */}
        <div className="mt-4 flex justify-end">
          <div className="w-full max-w-xs space-y-2 text-sm">
            <div className="flex justify-between text-neutral-500"><span>Subtotal</span><span>{formatPrice(inv.amountCents, inv.currency)}</span></div>
            <div className="flex justify-between text-neutral-500"><span>Tax</span><span>{formatPrice(0, inv.currency)}</span></div>
            <div className="flex justify-between border-t border-line pt-2 text-base font-bold text-[#1a1c3a]"><span>Total</span><span>{formatPrice(inv.amountCents, inv.currency)}</span></div>
            {inv.status === 'paid' && (
              <div className="flex justify-between font-semibold text-success-700"><span>Amount paid</span><span>{formatPrice(inv.amountCents, inv.currency)}</span></div>
            )}
          </div>
        </div>

        <p className="mt-10 border-t border-line pt-6 text-center text-xs text-neutral-400">
          Thank you for your business. This invoice was generated by {seller.name}. Questions? {seller.email || 'Contact support.'}
        </p>
      </div>
    </div>
  );
}
