import type { BlockDef, BlockType, FieldSpec } from './types';

const ALIGN: FieldSpec = {
  key: 'align',
  label: 'Alignment',
  type: 'select',
  options: [
    { value: 'left', label: 'Left' },
    { value: 'center', label: 'Center' },
    { value: 'right', label: 'Right' },
  ],
};

const BUTTON_STYLE: FieldSpec = {
  key: 'buttonStyle',
  label: 'Button style',
  type: 'select',
  options: [
    { value: 'solid', label: 'Solid' },
    { value: 'outline', label: 'Outline' },
    { value: 'soft', label: 'Soft' },
  ],
};

const RADIUS: FieldSpec = {
  key: 'cardRadius',
  label: 'Corner radius',
  type: 'select',
  options: [
    { value: 'sm', label: 'Small' },
    { value: 'lg', label: 'Medium' },
    { value: 'xl', label: 'Large' },
    { value: '2xl', label: 'Extra large' },
  ],
};

const SHADOW: FieldSpec = {
  key: 'shadow',
  label: 'Shadow',
  type: 'select',
  options: [
    { value: 'none', label: 'None' },
    { value: 'soft', label: 'Soft' },
    { value: 'lift', label: 'Lifted' },
  ],
};

const collectionFields = (extra: FieldSpec[] = []): FieldSpec[] => [
  { key: 'title', label: 'Section title', type: 'text', placeholder: 'e.g. Digital products' },
  {
    key: 'layout',
    label: 'Card layout',
    type: 'select',
    options: [
      { value: 'card', label: 'Stacked cards' },
      { value: 'horizontal', label: 'Horizontal card' },
      { value: 'horizontal-compact', label: 'Horizontal compact' },
      { value: 'list', label: 'Compact list' },
      { value: 'grid', label: 'Grid' },
    ],
  },
  { key: 'showImage', label: 'Show image', type: 'toggle' },
  { key: 'showRating', label: 'Show rating badge', type: 'toggle' },
  {
    key: 'ctaStyle',
    label: 'CTA style',
    type: 'select',
    options: [
      { value: 'solid', label: 'Solid accent' },
      { value: 'inverse', label: 'Light pill' },
      { value: 'neon', label: 'Bright (dark text)' },
      { value: 'outline', label: 'Outline' },
    ],
  },
  { key: 'showArrow', label: 'Show arrow on CTA', type: 'toggle' },
  { key: 'showPrice', label: 'Show price', type: 'toggle' },
  { key: 'showDescription', label: 'Show description', type: 'toggle' },
  { key: 'buttonLabel', label: 'Button label', type: 'text', placeholder: 'Buy now' },
  BUTTON_STYLE,
  RADIUS,
  SHADOW,
  { key: 'cardBg', label: 'Card background', type: 'color' },
  { key: 'accent', label: 'Accent override', type: 'color' },
  ...extra,
];

const collectionDefault = (title: string, buttonLabel: string) => ({
  title,
  layout: 'card',
  showImage: true,
  showPrice: true,
  showDescription: true,
  buttonLabel,
  buttonStyle: 'solid',
  cardRadius: 'xl',
  shadow: 'soft',
  cardBg: '',
  accent: '',
});

export const BLOCK_DEFS: Record<BlockType, BlockDef> = {
  header: {
    type: 'header',
    label: 'Profile header',
    emoji: '👤',
    category: 'profile',
    singleton: true,
    pinned: true,
    default: {
      align: 'center',
      avatarShape: 'circle',
      avatarSize: 112,
      banner: 'gradient',
      bannerHeight: 128,
      showCategory: true,
      showBio: true,
      showSocials: true,
      showHandle: false,
      showAvatar: true,
      profileLayout: 'stacked',
      socialStyle: 'pills',
      nameColor: '',
      bannerColor: '',
    },
    fields: [
      ALIGN,
      {
        key: 'profileLayout',
        label: 'Profile layout',
        type: 'select',
        options: [
          { value: 'stacked', label: 'Centered stack' },
          { value: 'inline', label: 'Avatar + name row' },
          { value: 'hero', label: 'Hero photo overlay' },
          { value: 'split', label: 'Split profile card' },
          { value: 'banner-row', label: 'Banner + name row' },
        ],
      },
      {
        key: 'socialStyle',
        label: 'Social links style',
        type: 'select',
        options: [
          { value: 'pills', label: 'Text pills' },
          { value: 'icons', label: 'Icon circles' },
          { value: 'outlined', label: 'Outlined squares' },
        ],
      },
      { key: 'showAvatar', label: 'Show avatar', type: 'toggle' },
      {
        key: 'avatarShape',
        label: 'Avatar shape',
        type: 'select',
        options: [
          { value: 'circle', label: 'Circle' },
          { value: 'rounded', label: 'Rounded' },
          { value: 'square', label: 'Square' },
        ],
      },
      { key: 'avatarSize', label: 'Avatar size', type: 'range', min: 64, max: 140, step: 4 },
      {
        key: 'banner',
        label: 'Banner',
        type: 'select',
        options: [
          { value: 'gradient', label: 'Gradient' },
          { value: 'solid', label: 'Solid' },
          { value: 'none', label: 'None' },
        ],
      },
      { key: 'bannerHeight', label: 'Banner height', type: 'range', min: 0, max: 220, step: 8 },
      { key: 'bannerColor', label: 'Banner color override', type: 'color' },
      { key: 'nameColor', label: 'Name color', type: 'color' },
      { key: 'showCategory', label: 'Show category', type: 'toggle' },
      { key: 'showBio', label: 'Show bio', type: 'toggle' },
      { key: 'showSocials', label: 'Show social icons', type: 'toggle' },
      { key: 'showHandle', label: 'Show @handle', type: 'toggle' },
    ],
  },
  featured: {
    type: 'featured',
    label: 'Featured offer',
    emoji: '⭐',
    category: 'offers',
    default: {
      headline: 'Start here',
      buttonLabel: 'Buy now',
      buttonStyle: 'solid',
      cardRadius: '2xl',
      shadow: 'lift',
      accent: '',
      itemSlug: '',
    },
    fields: [
      { key: 'headline', label: 'Badge text', type: 'text', placeholder: 'Start here' },
      { key: 'itemSlug', label: 'Featured item slug', type: 'text', placeholder: 'Leave empty for first item' },
      { key: 'buttonLabel', label: 'Button label', type: 'text' },
      BUTTON_STYLE,
      RADIUS,
      SHADOW,
      { key: 'accent', label: 'Accent override', type: 'color' },
    ],
  },
  product: {
    type: 'product',
    label: 'Digital products',
    emoji: '📦',
    category: 'offers',
    default: collectionDefault('Digital products', 'Buy now'),
    fields: collectionFields(),
  },
  course: {
    type: 'course',
    label: 'Courses',
    emoji: '🎓',
    category: 'offers',
    default: collectionDefault('Courses', 'View course'),
    fields: collectionFields(),
  },
  booking: {
    type: 'booking',
    label: 'Bookings',
    emoji: '📅',
    category: 'offers',
    default: collectionDefault('Book a call', 'Book a time'),
    fields: collectionFields(),
  },
  webinar: {
    type: 'webinar',
    label: 'Webinars',
    emoji: '🎥',
    category: 'offers',
    default: collectionDefault('Join a webinar', 'Register'),
    fields: collectionFields(),
  },
  leadMagnet: {
    type: 'leadMagnet',
    label: 'Free resources',
    emoji: '🎁',
    category: 'offers',
    default: collectionDefault('Free resources', 'Get it free'),
    fields: collectionFields(),
  },
  emailCapture: {
    type: 'emailCapture',
    label: 'Email signup',
    emoji: '✉️',
    category: 'offers',
    default: { heading: 'Stay in the loop', buttonLabel: 'Subscribe', bg: '', accent: '' },
    fields: [
      { key: 'heading', label: 'Heading', type: 'text' },
      { key: 'buttonLabel', label: 'Button label', type: 'text' },
      { key: 'bg', label: 'Background', type: 'color' },
      { key: 'accent', label: 'Accent override', type: 'color' },
    ],
  },
  links: {
    type: 'links',
    label: 'Social links',
    emoji: '🔗',
    category: 'offers',
    default: { title: '', layout: 'buttons' },
    fields: [
      { key: 'title', label: 'Section title', type: 'text' },
      {
        key: 'layout',
        label: 'Layout',
        type: 'select',
        options: [
          { value: 'buttons', label: 'Buttons' },
          { value: 'pills', label: 'Pills' },
        ],
      },
    ],
  },
  heading: {
    type: 'heading',
    label: 'Heading',
    emoji: '🔠',
    category: 'content',
    default: { text: 'Your heading', size: 'lg', align: 'center', color: '' },
    fields: [
      { key: 'text', label: 'Text', type: 'text' },
      {
        key: 'size',
        label: 'Size',
        type: 'select',
        options: [
          { value: 'sm', label: 'Small' },
          { value: 'md', label: 'Medium' },
          { value: 'lg', label: 'Large' },
          { value: 'xl', label: 'Extra large' },
        ],
      },
      ALIGN,
      { key: 'color', label: 'Color', type: 'color' },
    ],
  },
  text: {
    type: 'text',
    label: 'Text',
    emoji: '📝',
    category: 'content',
    default: { text: 'Write something for your visitors…', align: 'center', color: '', size: 'md' },
    fields: [
      { key: 'text', label: 'Text', type: 'textarea' },
      {
        key: 'size',
        label: 'Size',
        type: 'select',
        options: [
          { value: 'sm', label: 'Small' },
          { value: 'md', label: 'Medium' },
          { value: 'lg', label: 'Large' },
        ],
      },
      ALIGN,
      { key: 'color', label: 'Color', type: 'color' },
    ],
  },
  button: {
    type: 'button',
    label: 'Button',
    emoji: '🔘',
    category: 'content',
    default: {
      label: 'Click here',
      url: '',
      buttonStyle: 'solid',
      radius: 'full',
      bg: '',
      color: '',
      fullWidth: true,
      align: 'center',
    },
    fields: [
      { key: 'label', label: 'Label', type: 'text' },
      { key: 'url', label: 'Link URL', type: 'text', placeholder: 'https://…' },
      BUTTON_STYLE,
      {
        key: 'radius',
        label: 'Corners',
        type: 'select',
        options: [
          { value: 'lg', label: 'Rounded' },
          { value: 'full', label: 'Pill' },
        ],
      },
      { key: 'bg', label: 'Background', type: 'color' },
      { key: 'color', label: 'Text color', type: 'color' },
      { key: 'fullWidth', label: 'Full width', type: 'toggle' },
      ALIGN,
    ],
  },
  image: {
    type: 'image',
    label: 'Image',
    emoji: '🖼️',
    category: 'content',
    default: { url: '', radius: 'xl', fullWidth: true, link: '', caption: '' },
    fields: [
      { key: 'url', label: 'Image URL', type: 'text', placeholder: 'https://…' },
      {
        key: 'radius',
        label: 'Corners',
        type: 'select',
        options: [
          { value: 'none', label: 'Square' },
          { value: 'lg', label: 'Rounded' },
          { value: 'xl', label: 'Large' },
          { value: 'full', label: 'Circle' },
        ],
      },
      { key: 'fullWidth', label: 'Full width', type: 'toggle' },
      { key: 'link', label: 'Link URL', type: 'text' },
      { key: 'caption', label: 'Caption', type: 'text' },
    ],
  },
  divider: {
    type: 'divider',
    label: 'Divider',
    emoji: '➖',
    category: 'content',
    default: { style: 'line' },
    fields: [
      {
        key: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'line', label: 'Line' },
          { value: 'dots', label: 'Dots' },
          { value: 'space', label: 'Empty space' },
        ],
      },
    ],
  },
  hero: {
    type: 'hero',
    label: 'Hero / Callout',
    emoji: '🚀',
    category: 'content',
    default: {
      headline: 'Build something people love',
      subheadline: 'A short, punchy promise to your visitors.',
      ctaLabel: 'Get started',
      ctaUrl: '',
      imageUrl: '',
      align: 'center',
      bg: '',
      accent: '',
    },
    fields: [
      { key: 'headline', label: 'Headline', type: 'text' },
      { key: 'subheadline', label: 'Subheadline', type: 'textarea' },
      { key: 'imageUrl', label: 'Image URL', type: 'text', placeholder: 'https://…' },
      { key: 'ctaLabel', label: 'Button label', type: 'text' },
      { key: 'ctaUrl', label: 'Button link', type: 'text', placeholder: 'https://…' },
      ALIGN,
      { key: 'bg', label: 'Background', type: 'color' },
      { key: 'accent', label: 'Accent override', type: 'color' },
    ],
  },
  testimonial: {
    type: 'testimonial',
    label: 'Testimonial',
    emoji: '💬',
    category: 'content',
    default: {
      quote: 'This completely changed how I work — worth every penny.',
      author: 'Happy customer',
      role: '',
      avatarUrl: '',
      accent: '',
    },
    fields: [
      { key: 'quote', label: 'Quote', type: 'textarea' },
      { key: 'author', label: 'Author', type: 'text' },
      { key: 'role', label: 'Role / handle', type: 'text', placeholder: '@username or Founder, Acme' },
      { key: 'avatarUrl', label: 'Avatar URL', type: 'text', placeholder: 'https://…' },
      { key: 'accent', label: 'Accent override', type: 'color' },
    ],
  },
  faq: {
    type: 'faq',
    label: 'FAQ',
    emoji: '❓',
    category: 'content',
    default: {
      title: 'Frequently asked questions',
      items: [
        { q: 'How do I get access?', a: 'You’ll get an instant email with your link right after checkout.' },
        { q: 'Do you offer refunds?', a: 'Yes — reach out within 14 days and I’ll sort it out.' },
      ],
    },
    fields: [
      { key: 'title', label: 'Section title', type: 'text' },
      {
        key: 'items',
        label: 'Questions',
        type: 'repeater',
        addLabel: 'Add question',
        max: 12,
        columns: [
          { key: 'q', placeholder: 'Question' },
          { key: 'a', placeholder: 'Answer', multiline: true },
        ],
      },
    ],
  },
  gallery: {
    type: 'gallery',
    label: 'Gallery',
    emoji: '🖼️',
    category: 'content',
    default: {
      title: '',
      cardRadius: 'xl',
      images: [
        { url: '', link: '' },
        { url: '', link: '' },
      ],
    },
    fields: [
      { key: 'title', label: 'Section title', type: 'text' },
      RADIUS,
      {
        key: 'images',
        label: 'Images',
        type: 'repeater',
        addLabel: 'Add image',
        max: 8,
        columns: [
          { key: 'url', placeholder: 'Image URL' },
          { key: 'link', placeholder: 'Link URL (optional)' },
        ],
      },
    ],
  },
};

export const ADDABLE_BLOCKS: BlockType[] = [
  'product',
  'course',
  'booking',
  'webinar',
  'leadMagnet',
  'featured',
  'links',
  'emailCapture',
  'hero',
  'testimonial',
  'faq',
  'gallery',
  'heading',
  'text',
  'button',
  'image',
  'divider',
];
